//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTeam.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }


        public DbSet<uspUpdateLeaveBalances_Result> Employee { get; set; }


        public IQueryable<uspUpdateLeaveBalances_Result> GetEmployeeInfo(int BSID)
        {
            return Employee.Where(e => e.ID == BSID);
        }

        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Person> People { get; set; }
    
        public virtual ObjectResult<uspUpdateLeaveBalances_Result> uspUpdateLeaveBalances()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspUpdateLeaveBalances_Result>("uspUpdateLeaveBalances");
        }


    }
}
